name: ${project.artifactId}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
version: ${project.version}-Build#${env.BUILD_NUMBER}
authors:
- Netherfoam
- Timtower
- KaiNoMood
- 喵♂呜
softdepend:
- Vault
- WowSuchCleaner
website: ${jenkins.url}/job/${project.artifactId}/
commands:
  qs:
    description: QuickShop 命令
    usage: §c未知的子命令 请输入 §b/qs help §c查看帮助!
    aliases:
    - quickshop
    - shop
permissions:
  quickshop.create.sell:
    description: 允许玩家创建出售商店
    default: op
  quickshop.create.buy:
    description: 允许玩家创建收购商店
    default: op
  quickshop.create.double:
    description: 允许玩家创建双箱商店
    default: op
  quickshop.use:
    description: 允许玩家在其他商店交易
    default: true
  quickshop.unlimited:
    description: 允许玩家使用/qs unlimited创建无限商店
  quickshop.bypass.<itemID>:
    description: 允许玩家出售 <itemID>, 即使物品在黑名单里
  quickshop.other.destroy:
    description: 允许玩家摧毁其他玩家的商店
  quickshop.other.open:
    description: 允许玩家打开其他玩家的商店
  quickshop.other.price:
    description: 允许玩家修改商店的价格
  quickshop.setowner:
    description: 允许管理员设置商店的所有者
  quickshop.find:
    description: 允许玩家查找附近的商店 (限制在3个区块内工作)
    default: true
  quickshop.refill:
    description: 允许玩家填满商店库存
    default: op
  quickshop.empty:
    description: 允许玩家清空指定商店
    default: op
  quickshop.debug:
    description: 能够从控制台收到调试信息
    default: op
  quickshop.export:
    description: 允许导出数据到SQLite或者MySQL
    default: op